import type { Metadata } from "next";
import React from "react";
import RootLayout from "./RootLayout";
import { env } from "@/utils/env";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function layout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en">
            <body>
                <RootLayout env={env}>
                    {children}
                </RootLayout>
            </body>
        </html>
    );
}
